### ISSUE TITLE
Call to action link

### ISSUE THREAD

**Issue by afragen** [costdev/wp-virtualbox-testing#1]
Should the link at the bottom of the readme be to the main call to action post or the VB specific call to action post?

**Comment by costdev** [comment]
The link at the bottom of `readme.md` should be to the main Call for Testing post, which will link to this repo.

By providing a link back to the post:
- This allows VirtualBox testers to continue where they left off.
  - As we don't use `target="_blank"` on links on wordpress.org, this allows VirtualBox testers to seamlessly navigate from **Call for Testing > Repo > Call for Testing** within a single tab, and without the need for clicking "Back".
- If anyone gets sent a link directly to this repo, they can still proceed to the Call for Testing from this repo.
